name: CI-Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Directories & Files
        run: ls -l

      - name: Run tests
        run: npm test

      # 🚨 INTENTIONAL MISTAKES FOR TESTING SECRETS EXPOSURE

      - name: Echo dummy secret in plain text (bad practice)
        run: echo "API_KEY=12345-SECRET-KEY-EXPOSED"

      - name: Use secret as ENV variable but print it (bad practice)
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "Using secret key..."
          echo "Secret Key: $MY_SECRET_KEY"
